# Generated by Django 2.2.11 on 2020-03-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('emp_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
